apiVersion: v1
kind: Service
metadata:
  name: leaderboard-svc
  namespace: leaderboard
spec:
  selector:
    app: leaderboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-deploy
  namespace: leaderboard
spec:
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: 420615923610.dkr.ecr.ap-northeast-2.amazonaws.com/dga-leaderboard:13
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 50m
