apiVersion: v1
kind: Service
metadata:
  name: search-svc
  namespace: search
spec:
  selector:
    app: search
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deploy
  namespace: search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: 420615923610.dkr.ecr.ap-northeast-2.amazonaws.com/dga-search:7
