apiVersion: v1
kind: Service
metadata:
  name: board-svc
  namespace: board
spec:
  selector:
    app: board
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8085
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-deploy
  namespace: board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: 420615923610.dkr.ecr.ap-northeast-2.amazonaws.com/dga-board:35
