apiVersion: v1
kind: Service
metadata:
  name: member-svc
  namespace: member
spec:
  selector:
    app: member
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deploy
  namespace: member
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: 420615923610.dkr.ecr.ap-northeast-2.amazonaws.com/dga-member:44
